import React, { useState } from 'react';
import {
  X,
  FileText,
  BadgeCheck,
  Building2,
  Lock,
  ChevronLeft,
  ChevronRight,
  ShieldCheck,
  Sparkles,
  ArrowRight,
  Landmark,
} from 'lucide-react';
import { Dialog } from '@tableview/ui';

interface DossierSamplePreviewModalProps {
  isOpen: boolean;
  onClose: () => void;
  onUnlockClick?: () => void;
}

export const DossierSamplePreviewModal: React.FC<DossierSamplePreviewModalProps> = ({
  isOpen,
  onClose,
  onUnlockClick,
}) => {
  const [currentPage, setCurrentPage] = useState<number>(1);

  if (!isOpen) return null;

  return (
    <Dialog
      onClose={onClose}
      labelledBy="dossier-sample-modal-title"
      overlayClassName="fixed inset-0 z-50 overflow-y-auto p-2 sm:p-4 bg-slate-950/75 backdrop-blur-xs flex justify-center items-center animate-in fade-in duration-200"
      panelClassName="relative w-full max-w-4xl bg-slate-900 rounded-2xl shadow-2xl border border-slate-700 overflow-hidden my-auto flex flex-col max-h-[92vh]"
    >
      {/* Header */}
      <div className="px-5 py-4 border-b border-slate-800 bg-slate-900 flex items-center justify-between shrink-0">
        <div className="flex items-center gap-2.5">
          <div className="p-1.5 rounded-lg bg-indigo-500/20 text-indigo-400 border border-indigo-400/30">
            <FileText className="size-4" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h3 id="dossier-sample-modal-title" className="text-sm sm:text-base font-bold text-white tracking-tight">
                Live Sample: 4-Page Institutional Dossier
              </h3>
              <span className="px-2 py-0.5 rounded-full text-[10px] font-black uppercase bg-amber-400 text-amber-950">
                Sample Preview
              </span>
            </div>
            <p className="text-[11px] text-slate-400">
              Exact deliverable generated by TableView. Unlocked versions include your custom branding &amp; 0 watermarks.
            </p>
          </div>
        </div>
        <button
          onClick={onClose}
          className="p-1.5 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition-colors cursor-pointer"
          aria-label="Close Preview"
        >
          <X className="size-5" />
        </button>
      </div>

      {/* Page Navigation Tabs */}
      <div className="px-5 py-2.5 bg-slate-950/80 border-b border-slate-800 flex items-center justify-between gap-2 overflow-x-auto shrink-0">
        <div className="flex items-center gap-1.5">
          {[
            { page: 1, label: 'Page 1: Executive Cover & Broker Card' },
            { page: 2, label: 'Page 2: CFPB QM 28/43% Audit' },
            { page: 3, label: 'Page 3: Itemized Cash-to-Close' },
            { page: 4, label: 'Page 4: 360-Mo Amortization Schedule' },
          ].map((tab) => (
            <button
              key={tab.page}
              onClick={() => setCurrentPage(tab.page)}
              className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all cursor-pointer whitespace-nowrap flex items-center gap-1.5 ${
                currentPage === tab.page
                  ? 'bg-indigo-600 text-white shadow-xs'
                  : 'text-slate-400 hover:text-slate-200 hover:bg-slate-800/80'
              }`}
            >
              <span>{tab.label}</span>
            </button>
          ))}
        </div>

        <div className="flex items-center gap-1 text-slate-400 text-xs">
          <button
            onClick={() => setCurrentPage((p) => Math.max(1, p - 1))}
            disabled={currentPage === 1}
            className="p-1 rounded hover:bg-slate-800 disabled:opacity-30 cursor-pointer"
            aria-label="Previous Page"
          >
            <ChevronLeft className="size-4" />
          </button>
          <span className="font-mono text-[11px] font-bold px-1.5 text-slate-300">
            {currentPage} / 4
          </span>
          <button
            onClick={() => setCurrentPage((p) => Math.min(4, p + 1))}
            disabled={currentPage === 4}
            className="p-1 rounded hover:bg-slate-800 disabled:opacity-30 cursor-pointer"
            aria-label="Next Page"
          >
            <ChevronRight className="size-4" />
          </button>
        </div>
      </div>

      {/* Main Document Body (Paper simulation) */}
      <div className="flex-1 overflow-y-auto p-4 sm:p-6 bg-slate-950 flex justify-center">
        <div className="w-full max-w-2xl bg-white text-slate-900 rounded-xl shadow-2xl p-6 sm:p-8 relative border border-slate-200 min-h-[560px] flex flex-col justify-between font-sans">
          {/* Diagonal Watermark Overlay */}
          <div className="absolute inset-0 pointer-events-none overflow-hidden flex items-center justify-center opacity-7">
            <span className="text-4xl sm:text-6xl font-black uppercase text-slate-900 rotate-[-25deg] select-none tracking-widest">
              SAMPLE DELIVERABLE
            </span>
          </div>

          {/* PAGE 1: Executive Cover & Custom Broker Card */}
          {currentPage === 1 && (
            <div className="space-y-6">
              {/* White-Label Broker Header */}
              <div className="border-b-2 border-slate-900 pb-4 flex justify-between items-start gap-4">
                <div className="flex items-center gap-3">
                  <div className="size-11 rounded-lg bg-indigo-900 text-white font-black text-xl flex items-center justify-center border border-indigo-700 shrink-0">
                    A
                  </div>
                  <div>
                    <div className="flex items-center gap-2">
                      <span className="text-lg font-black tracking-tight text-slate-950 uppercase">
                        Apex Capital Mortgage Group
                      </span>
                      <span className="text-[10px] px-1.5 py-0.2 rounded bg-slate-100 text-slate-700 font-semibold border border-slate-300 font-mono">
                        NMLS #1849201
                      </span>
                    </div>
                    <div className="text-xs font-bold text-indigo-950">
                      Prepared by: Marcus Vance, VP Lending
                    </div>
                    <div className="text-[10px] text-slate-500">
                      marcus@apexcapitalmortgage.com · (415) 890-2100
                    </div>
                  </div>
                </div>

                <div className="text-right shrink-0">
                  <div className="inline-block px-2 py-0.5 rounded bg-emerald-100 text-emerald-900 border border-emerald-300 text-[10px] font-extrabold uppercase">
                    QM Underwriter Certified
                  </div>
                  <div className="text-[10px] text-slate-400 mt-1 font-mono">
                    Ref ID: MTG-750K-2026-QM
                  </div>
                </div>
              </div>

              {/* Title & Property Specs */}
              <div>
                <span className="text-[10px] font-bold uppercase tracking-wider text-slate-500 font-mono">
                  Official Institutional Pre-Approval Dossier
                </span>
                <h4 className="text-2xl font-black text-slate-950 tracking-tight mt-0.5">
                  Residential Mortgage Underwriting Statement
                </h4>
                <p className="text-xs text-slate-600 mt-1">
                  Property Asset: 742 Evergreen Terrace, Springfield, OR · Primary Single-Family Residence
                </p>
              </div>

              {/* Key Scenario Metric Grid */}
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 bg-slate-50 p-3.5 rounded-xl border border-slate-200">
                <div>
                  <div className="text-[10px] text-slate-500 font-medium">Purchase Price</div>
                  <div className="text-base font-black text-slate-900">$750,000</div>
                </div>
                <div>
                  <div className="text-[10px] text-slate-500 font-medium">Down Payment (20%)</div>
                  <div className="text-base font-black text-slate-900">$150,000</div>
                </div>
                <div>
                  <div className="text-[10px] text-slate-500 font-medium">Loan Amount</div>
                  <div className="text-base font-black text-indigo-950">$600,000</div>
                </div>
                <div>
                  <div className="text-[10px] text-slate-500 font-medium">Interest Rate &amp; Term</div>
                  <div className="text-base font-black text-indigo-950">6.375% · 30Y Fixed</div>
                </div>
              </div>

              {/* PITI Monthly Payment Breakdown Card */}
              <div className="border border-indigo-200 rounded-xl p-4 bg-indigo-50/40">
                <div className="flex items-center justify-between mb-2">
                  <span className="text-xs font-bold text-indigo-950 uppercase tracking-wide">
                    Total Monthly Housing Payment (PITI + HOA)
                  </span>
                  <span className="text-xl font-black text-indigo-950 font-mono">
                    $4,643.82<span className="text-xs text-slate-500 font-normal"> / mo</span>
                  </span>
                </div>
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 text-xs border-t border-indigo-200/60 pt-2 text-slate-700">
                  <div>Principal &amp; Interest: <strong>$3,743.82</strong></div>
                  <div>Property Taxes: <strong>$750.00</strong></div>
                  <div>Home Insurance: <strong>$150.00</strong></div>
                  <div>PMI: <strong>$0.00 (Waived)</strong></div>
                </div>
              </div>

              {/* AI Deal Memo Executive Summary Preview */}
              <div className="p-3.5 rounded-xl bg-slate-50 border border-slate-200 space-y-1">
                <div className="flex items-center gap-1.5 text-xs font-bold text-slate-900">
                  <Sparkles className="size-3.5 text-amber-500" />
                  <span>Underwriter Deal Memo Executive Summary</span>
                </div>
                <p className="text-[11px] text-slate-600 leading-relaxed">
                  Borrower demonstrates Tier-1 prime credit profile (760+ FICO) with clean 20% equity participation. Front-end housing ratio settles comfortably at 23.4% against eligible qualifying income, with back-end DTI well below the 43.0% statutory threshold. Fully compliant with CFPB Qualified Mortgage standards.
                </p>
              </div>
            </div>
          )}

          {/* PAGE 2: CFPB Qualified Mortgage (QM) 28/43% Audit */}
          {currentPage === 2 && (
            <div className="space-y-6">
              <div className="border-b-2 border-slate-900 pb-3 flex items-center justify-between">
                <div>
                  <h4 className="text-lg font-black text-slate-950 uppercase tracking-tight">
                    CFPB Qualified Mortgage (QM) Audit
                  </h4>
                  <p className="text-[11px] text-slate-500">
                    Regulation Z · 12 CFR § 1026.43 Ability-to-Repay (ATR) Safe Harbor Assessment
                  </p>
                </div>
                <span className="px-2.5 py-1 rounded-full bg-emerald-100 text-emerald-800 border border-emerald-300 text-[10px] font-black uppercase flex items-center gap-1">
                  <BadgeCheck className="size-3.5" />
                  QM Compliant
                </span>
              </div>

              {/* DTI Audit Table */}
              <div className="border border-slate-200 rounded-xl overflow-hidden">
                <table className="w-full text-left text-xs border-collapse">
                  <thead>
                    <tr className="bg-slate-100/80 text-slate-600 font-mono text-[10px] uppercase border-b border-slate-200">
                      <th className="py-2.5 px-3">Underwriting Parameter</th>
                      <th className="py-2.5 px-3 text-right">Eligible Amount</th>
                      <th className="py-2.5 px-3 text-right">Regulatory Limit</th>
                      <th className="py-2.5 px-3 text-center">Audit Verdict</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-100 text-slate-700">
                    <tr>
                      <td className="py-2.5 px-3 font-medium">Front-End Housing Ratio (PITI / Income)</td>
                      <td className="py-2.5 px-3 text-right font-mono font-bold text-slate-900">23.4%</td>
                      <td className="py-2.5 px-3 text-right text-slate-500">28.0% Max</td>
                      <td className="py-2.5 px-3 text-center">
                        <span className="px-2 py-0.5 rounded-full bg-emerald-100 text-emerald-800 text-[10px] font-extrabold uppercase">
                          PASS
                        </span>
                      </td>
                    </tr>
                    <tr>
                      <td className="py-2.5 px-3 font-medium">Back-End Debt-to-Income (Total Debt / Income)</td>
                      <td className="py-2.5 px-3 text-right font-mono font-bold text-slate-900">34.8%</td>
                      <td className="py-2.5 px-3 text-right text-slate-500">43.0% Max</td>
                      <td className="py-2.5 px-3 text-center">
                        <span className="px-2 py-0.5 rounded-full bg-emerald-100 text-emerald-800 text-[10px] font-extrabold uppercase">
                          PASS
                        </span>
                      </td>
                    </tr>
                    <tr>
                      <td className="py-2.5 px-3 font-medium">Points &amp; Fees Statutory Cap (QM Standard)</td>
                      <td className="py-2.5 px-3 text-right font-mono text-slate-900">1.12%</td>
                      <td className="py-2.5 px-3 text-right text-slate-500">3.00% Max</td>
                      <td className="py-2.5 px-3 text-center">
                        <span className="px-2 py-0.5 rounded-full bg-emerald-100 text-emerald-800 text-[10px] font-extrabold uppercase">
                          PASS
                        </span>
                      </td>
                    </tr>
                    <tr>
                      <td className="py-2.5 px-3 font-medium">Negative Amortization or Balloon Clause</td>
                      <td className="py-2.5 px-3 text-right text-slate-900">None</td>
                      <td className="py-2.5 px-3 text-right text-slate-500">Prohibited</td>
                      <td className="py-2.5 px-3 text-center">
                        <span className="px-2 py-0.5 rounded-full bg-emerald-100 text-emerald-800 text-[10px] font-extrabold uppercase">
                          PASS
                        </span>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>

              {/* Regulatory Notice Banner */}
              <div className="p-3 rounded-xl bg-slate-50 border border-slate-200 text-[11px] text-slate-600 space-y-1">
                <div className="font-bold text-slate-900 flex items-center gap-1.5">
                  <ShieldCheck className="size-3.5 text-indigo-600" />
                  <span>ATR Safe Harbor Protection Notice</span>
                </div>
                <p>
                  This underwriter audit certifies that the debt payload complies with federal Qualified Mortgage thresholds under 12 CFR § 1026.43, preserving lender safe harbor protections against legal recourse.
                </p>
              </div>
            </div>
          )}

          {/* PAGE 3: Itemized Cash-to-Close & Settlement Audit */}
          {currentPage === 3 && (
            <div className="space-y-6">
              <div className="border-b-2 border-slate-900 pb-3 flex items-center justify-between">
                <div>
                  <h4 className="text-lg font-black text-slate-950 uppercase tracking-tight">
                    Itemized Cash-to-Close Audit
                  </h4>
                  <p className="text-[11px] text-slate-500">
                    TRID-compliant settlement cost accounting &amp; prepaids schedule
                  </p>
                </div>
                <span className="font-mono text-base font-black text-slate-900">
                  Total: $159,837
                </span>
              </div>

              {/* Settlement Line Items */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-xs">
                <div className="border border-slate-200 rounded-xl p-3.5 space-y-2 bg-slate-50/50">
                  <div className="font-bold text-slate-900 text-[11px] uppercase tracking-wide text-indigo-950 border-b border-slate-200 pb-1">
                    A. Down Payment &amp; Origination
                  </div>
                  <div className="flex justify-between">
                    <span className="text-slate-600">Contract Down Payment (20%)</span>
                    <span className="font-mono font-bold">$150,000.00</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-slate-600">Lender Underwriting Fee</span>
                    <span className="font-mono">$1,295.00</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-slate-600">Loan Processing &amp; Setup</span>
                    <span className="font-mono">$850.00</span>
                  </div>
                </div>

                <div className="border border-slate-200 rounded-xl p-3.5 space-y-2 bg-slate-50/50">
                  <div className="font-bold text-slate-900 text-[11px] uppercase tracking-wide text-indigo-950 border-b border-slate-200 pb-1">
                    B. Third-Party Closing &amp; Title
                  </div>
                  <div className="flex justify-between">
                    <span className="text-slate-600">Appraisal &amp; Inspection</span>
                    <span className="font-mono">$650.00</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-slate-600">Lender Title Insurance Policy</span>
                    <span className="font-mono">$1,420.00</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-slate-600">Escrow &amp; Settlement Closing Fee</span>
                    <span className="font-mono">$850.00</span>
                  </div>
                </div>

                <div className="border border-slate-200 rounded-xl p-3.5 space-y-2 bg-slate-50/50">
                  <div className="font-bold text-slate-900 text-[11px] uppercase tracking-wide text-indigo-950 border-b border-slate-200 pb-1">
                    C. Prepaids &amp; Interim Interest
                  </div>
                  <div className="flex justify-between">
                    <span className="text-slate-600">Prepaid Interest (15 days @ 6.375%)</span>
                    <span className="font-mono">$1,572.00</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-slate-600">12-Mo Homeowners Insurance Policy</span>
                    <span className="font-mono">$1,400.00</span>
                  </div>
                </div>

                <div className="border border-slate-200 rounded-xl p-3.5 space-y-2 bg-slate-50/50">
                  <div className="font-bold text-slate-900 text-[11px] uppercase tracking-wide text-indigo-950 border-b border-slate-200 pb-1">
                    D. Initial Escrow Reserves
                  </div>
                  <div className="flex justify-between">
                    <span className="text-slate-600">Property Tax Impound (2 Months)</span>
                    <span className="font-mono">$1,500.00</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-slate-600">Hazard Insurance Impound (2 Months)</span>
                    <span className="font-mono">$300.00</span>
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* PAGE 4: 360-Month Comprehensive Amortization Schedule */}
          {currentPage === 4 && (
            <div className="space-y-6">
              <div className="border-b-2 border-slate-900 pb-3 flex items-center justify-between">
                <div>
                  <h4 className="text-lg font-black text-slate-950 uppercase tracking-tight">
                    360-Month Amortization Schedule
                  </h4>
                  <p className="text-[11px] text-slate-500">
                    Annual milestone summaries &amp; cumulative equity paydown model
                  </p>
                </div>
                <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400 font-mono">
                  Full 30-Year Horizon
                </span>
              </div>

              {/* Amortization Milestone Table */}
              <div className="border border-slate-200 rounded-xl overflow-hidden">
                <table className="w-full text-left text-xs border-collapse">
                  <thead>
                    <tr className="bg-slate-100/80 text-slate-600 font-mono text-[10px] uppercase border-b border-slate-200">
                      <th className="py-2 px-3">Year</th>
                      <th className="py-2 px-3 text-right">Principal Paid</th>
                      <th className="py-2 px-3 text-right">Interest Paid</th>
                      <th className="py-2 px-3 text-right">Remaining Balance</th>
                      <th className="py-2 px-3 text-right">Home Equity</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-100 text-slate-700 font-mono">
                    <tr>
                      <td className="py-2 px-3 font-bold text-slate-900">Year 1</td>
                      <td className="py-2 px-3 text-right font-medium">$6,849</td>
                      <td className="py-2 px-3 text-right text-rose-700">$38,077</td>
                      <td className="py-2 px-3 text-right text-slate-900">$593,151</td>
                      <td className="py-2 px-3 text-right font-bold text-emerald-700">$156,849</td>
                    </tr>
                    <tr>
                      <td className="py-2 px-3 font-bold text-slate-900">Year 5</td>
                      <td className="py-2 px-3 text-right font-medium">$39,788</td>
                      <td className="py-2 px-3 text-right text-rose-700">$184,841</td>
                      <td className="py-2 px-3 text-right text-slate-900">$560,212</td>
                      <td className="py-2 px-3 text-right font-bold text-emerald-700">$189,788</td>
                    </tr>
                    <tr>
                      <td className="py-2 px-3 font-bold text-slate-900">Year 10</td>
                      <td className="py-2 px-3 text-right font-medium">$94,528</td>
                      <td className="py-2 px-3 text-right text-rose-700">$354,730</td>
                      <td className="py-2 px-3 text-right text-slate-900">$505,472</td>
                      <td className="py-2 px-3 text-right font-bold text-emerald-700">$244,528</td>
                    </tr>
                    <tr>
                      <td className="py-2 px-3 font-bold text-slate-900">Year 20</td>
                      <td className="py-2 px-3 text-right font-medium">$269,778</td>
                      <td className="py-2 px-3 text-right text-rose-700">$628,738</td>
                      <td className="py-2 px-3 text-right text-slate-900">$330,222</td>
                      <td className="py-2 px-3 text-right font-bold text-emerald-700">$419,778</td>
                    </tr>
                    <tr className="bg-indigo-50/50">
                      <td className="py-2 px-3 font-bold text-indigo-950">Year 30 (Maturity)</td>
                      <td className="py-2 px-3 text-right font-bold text-indigo-950">$600,000</td>
                      <td className="py-2 px-3 text-right text-rose-700">$747,775</td>
                      <td className="py-2 px-3 text-right font-bold text-emerald-700">$0</td>
                      <td className="py-2 px-3 text-right font-bold text-emerald-700">$750,000 (100%)</td>
                    </tr>
                  </tbody>
                </table>
              </div>

              {/* Dynamic Excel Note */}
              <div className="p-3 rounded-xl bg-slate-50 border border-slate-200 text-[11px] text-slate-600 flex items-center gap-2">
                <FileText className="size-4 text-emerald-700 shrink-0" />
                <span>
                  <strong>Included in Export Package:</strong> Full dynamic Excel workbook (.xlsx) with live monthly PMT, PPMT, and IPMT formulas for all 360 periods with 0 download limits.
                </span>
              </div>
            </div>
          )}

          {/* Footer of the Paper Sheet */}
          <div className="border-t border-slate-200 pt-3 mt-6 flex justify-between items-center text-[10px] text-slate-400">
            <span>TableView Institutional Underwriting Suite · Model v4.8</span>
            <span>Page {currentPage} of 4</span>
          </div>
        </div>
      </div>

      {/* Modal Bottom Action Bar */}
      <div className="px-6 py-4 border-t border-slate-800 bg-slate-900/90 flex flex-col sm:flex-row items-center justify-between gap-3 shrink-0">
        <div className="text-xs text-slate-300 text-center sm:text-left">
          <span>✨ Like this report? Export it instantly with <strong>zero watermarks</strong> &amp; <strong>custom branding</strong>.</span>
        </div>

        <div className="flex items-center gap-2.5 w-full sm:w-auto">
          <button
            type="button"
            onClick={onClose}
            className="flex-1 sm:flex-none px-4 py-2 rounded-xl text-xs font-semibold text-slate-400 hover:text-white hover:bg-slate-800 transition-colors cursor-pointer"
          >
            Close Preview
          </button>
          {onUnlockClick && (
            <button
              type="button"
              onClick={() => {
                onClose();
                onUnlockClick();
              }}
              className="flex-1 sm:flex-none px-5 py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-bold shadow-md hover:shadow-indigo-500/25 transition-all flex items-center justify-center gap-1.5 cursor-pointer"
            >
              <span>Unlock Official Dossier ($9.99 / Pro)</span>
              <ArrowRight className="size-3.5" />
            </button>
          )}
        </div>
      </div>
    </Dialog>
  );
};
