import { useState, useMemo, useEffect } from 'react';
import * as XLSX from 'xlsx';
import {
  Building2,
  Download,
  AlertTriangle,
  ShieldCheck,
  ChevronDown,
  Share2,
  Check,
  ArrowRight
} from 'lucide-react';
import {
  calculateCommercialLoan,
  type CommercialLoanInputs
} from '../lib/commercialLoanCalculator';
import { updatePageMeta, navigateTo } from '../lib/router';
import { CurrencyInput } from '../components/CurrencyInput';
import { NumericInput } from '../components/NumericInput';
import { MethodologyDisclosure } from '../components/MethodologyDisclosure';
import { RelatedCalculators } from '../components/RelatedCalculators';
import { AdSlot } from '../components/AdSlot';

const commercialLoanSchemas = [
  {
    '@type': 'WebApplication',
    name: 'Commercial Real Estate Loan & Balloon Payment Calculator',
    url: 'https://tableview.dev/commercial-loan-calculator',
    description: 'Free in-browser commercial real estate loan calculator. Model commercial mortgages with 5, 7, or 10-year balloon payments, 20-30 year amortization, interest-only options, and refinance risk assessment.',
    applicationCategory: 'FinanceApplication',
    operatingSystem: 'All',
    offers: {
      '@type': 'Offer',
      price: '0',
      priceCurrency: 'USD'
    }
  },
  {
    '@type': 'FinancialProduct',
    name: 'Commercial Mortgage Balloon Modeler',
    description: 'Underwriting and amortization tool for commercial real estate loans, retail spaces, multifamily, and SBA 504/7(a) debt.',
    category: 'CommercialMortgage'
  }
];

export const CommercialLoanCalculator = () => {
  useEffect(() => {
    updatePageMeta(
      'Commercial Loan & Balloon Payment Calculator — CRE Mortgage Modeling',
      'Calculate commercial mortgage payments, balloon payment due amounts, amortization schedules, and refinance risk. Free in-browser tool with Excel schedule export.',
      '/commercial-loan-calculator',
      commercialLoanSchemas
    );
  }, []);

  const [inputs, setInputs] = useState<CommercialLoanInputs>(() => {
    if (typeof window !== 'undefined') {
      const p = new URLSearchParams(window.location.search);
      return {
        propertyPrice: p.has('price') ? Number(p.get('price')) : 1500000,
        downPaymentPercent: p.has('down') ? Number(p.get('down')) : 25,
        interestRate: p.has('rate') ? Number(p.get('rate')) : 7.25,
        amortizationYears: p.has('amort') ? Number(p.get('amort')) : 25,
        balloonTermYears: p.has('balloon') ? Number(p.get('balloon')) : 5,
        interestOnlyMonths: p.has('io') ? Number(p.get('io')) : 0,
        originationPoints: p.has('points') ? Number(p.get('points')) : 1.0,
        closingFees: p.has('fees') ? Number(p.get('fees')) : 8500
      };
    }
    return {
      propertyPrice: 1500000,
      downPaymentPercent: 25,
      interestRate: 7.25,
      amortizationYears: 25,
      balloonTermYears: 5,
      interestOnlyMonths: 0,
      originationPoints: 1.0,
      closingFees: 8500
    };
  });

  const [copied, setCopied] = useState(false);
  const [openFaq, setOpenFaq] = useState<number | null>(0);

  const handleCopyLink = () => {
    const params = new URLSearchParams();
    params.set('price', String(inputs.propertyPrice));
    params.set('down', String(inputs.downPaymentPercent));
    params.set('rate', String(inputs.interestRate));
    params.set('amort', String(inputs.amortizationYears));
    params.set('balloon', String(inputs.balloonTermYears));
    if (inputs.interestOnlyMonths) params.set('io', String(inputs.interestOnlyMonths));
    if (inputs.originationPoints) params.set('points', String(inputs.originationPoints));
    if (inputs.closingFees) params.set('fees', String(inputs.closingFees));

    const url = `${window.location.origin}/commercial-loan-calculator?${params.toString()}`;
    navigator.clipboard.writeText(url);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const summary = useMemo(() => {
    return calculateCommercialLoan(inputs);
  }, [inputs]);

  const handleExportExcel = () => {
    const wb = XLSX.utils.book_new();

    const summarySheet = [
      ['Commercial Real Estate Loan & Balloon Schedule', 'Generated by TableView.dev'],
      ['Date', new Date().toLocaleDateString()],
      [],
      ['Property Purchase Price', `$${inputs.propertyPrice.toLocaleString()}`],
      ['Down Payment Amount', `$${summary.downPaymentAmount.toLocaleString()} (${inputs.downPaymentPercent}%)`],
      ['Loan Amount (LTV)', `$${summary.loanAmount.toLocaleString()} (${summary.ltv}%)`],
      ['Interest Rate (APR)', `${inputs.interestRate}%`],
      ['Amortization Schedule', `${inputs.amortizationYears} Years`],
      ['Balloon Note Term', `${inputs.balloonTermYears} Years`],
      ['Interest-Only Period', `${inputs.interestOnlyMonths || 0} Months`],
      [],
      ['Regular Monthly Payment (P&I)', `$${summary.regularMonthlyPayment.toLocaleString()}`],
      summary.interestOnlyMonths ? ['Initial Interest-Only Payment', `$${summary.interestOnlyMonthlyPayment.toLocaleString()}`] : [],
      ['Balloon Lump Sum Due at Maturity', `$${summary.balloonDueAmount.toLocaleString()} (${summary.balloonDuePercentOfOriginal}% of original debt)`],
      ['Principal Paid Before Balloon', `$${summary.totalPrincipalBeforeBalloon.toLocaleString()}`],
      ['Interest Paid Before Balloon', `$${summary.totalInterestBeforeBalloon.toLocaleString()}`],
      ['Total Upfront Fees & Points', `$${summary.upfrontCosts.toLocaleString()}`],
      [],
      ['Refinance Risk Level', summary.refinanceRiskLevel],
      ['Refinance Analysis', summary.refinanceAnalysis]
    ].filter(r => r.length > 0);

    const wsSummary = XLSX.utils.aoa_to_sheet(summarySheet);
    XLSX.utils.book_append_sheet(wb, wsSummary, 'Deal Summary');

    const scheduleHeaders = ['Year', 'Annual Payments ($)', 'Principal Paid ($)', 'Interest Paid ($)', 'Ending Balance ($)'];
    const scheduleRows = summary.yearlySchedule.map(y => [
      y.year,
      y.paymentsTotal,
      y.principalTotal,
      y.interestTotal,
      y.endingBalance
    ]);

    const wsSchedule = XLSX.utils.aoa_to_sheet([scheduleHeaders, ...scheduleRows]);
    XLSX.utils.book_append_sheet(wb, wsSchedule, 'Amortization Schedule');

    XLSX.writeFile(wb, 'Commercial_Loan_Balloon_Analysis.xlsx');
  };

  const faqs = [
    {
      q: 'What is a balloon payment in commercial real estate?',
      a: 'Unlike residential 30-year fixed mortgages, commercial real estate loans typically have a maturity term (e.g. 5 or 10 years) that is much shorter than their amortization schedule (e.g. 25 years). When the note matures, the remaining unpaid principal balance must be paid as a lump sum ("balloon payment"), usually requiring refinancing or sale of the asset.'
    },
    {
      q: 'Why do commercial lenders use balloon payments instead of 30-year fixed terms?',
      a: 'Commercial banks want to limit their interest rate risk over decades and re-underwrite properties periodically according to updated net operating income (NOI), tenancy rolls, and commercial market valuations.'
    },
    {
      q: 'How do I mitigate commercial balloon payment refinance risk?',
      a: 'Begin working with commercial mortgage brokers 6 to 12 months before your balloon maturity date. Maintain strong lease agreements, minimize tenant vacancies, and ensure property net operating income meets local lender DSCR requirements (typically 1.25x+).'
    }
  ];

  return (
    <div className="w-full max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10">
      {/* Header & Breadcrumbs */}
      <div className="mb-8">
        <div className="flex items-center gap-2 text-xs font-medium text-slate-400 mb-3">
          <button onClick={() => navigateTo('/')} className="hover:text-indigo-400 transition-colors cursor-pointer">Home</button>
          <span>/</span>
          <button onClick={() => navigateTo('/finance-calculator')} className="hover:text-indigo-400 transition-colors cursor-pointer">Calculators</button>
          <span>/</span>
          <span className="text-slate-200">Commercial Real Estate</span>
        </div>

        <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4">
          <div>
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full text-xs font-semibold bg-cyan-500/10 border border-cyan-500/20 text-cyan-400 mb-3">
              <Building2 className="size-3.5" />
              <span>Commercial Real Estate & Balloon Modeler</span>
            </div>
            <h1 className="text-3xl sm:text-4xl font-extrabold text-slate-100 tracking-tight">
              Commercial Loan & Balloon Payment Calculator
            </h1>
            <p className="text-sm sm:text-base text-slate-400 mt-2 max-w-2xl leading-relaxed">
              Model commercial mortgages with 5, 7, or 10-year balloon maturities against 20–30 year amortization schedules. Calculate regular monthly payments, maturity lump sums, and refinancing risks.
            </p>
          </div>

          <div className="flex flex-col sm:flex-row items-start sm:items-center gap-2.5 shrink-0">
            <button
              onClick={handleCopyLink}
              className="px-3.5 py-2.5 rounded-xl text-xs font-semibold inline-flex items-center gap-2 bg-slate-900 hover:bg-slate-800 text-slate-200 border border-slate-700/80 cursor-pointer transition-all shadow-sm"
              title="Copy shareable link with current commercial loan parameters"
            >
              {copied ? (
                <>
                  <Check className="size-4 text-emerald-400" />
                  <span className="text-emerald-400">Link Copied!</span>
                </>
              ) : (
                <>
                  <Share2 className="size-4 text-cyan-400" />
                  <span>Share Deal</span>
                </>
              )}
            </button>

            <button
              onClick={handleExportExcel}
              className="btn-primary px-4 py-2.5 rounded-xl text-xs font-semibold inline-flex items-center gap-2 shadow-md cursor-pointer transition-transform active:scale-95"
            >
              <Download className="size-4" />
              <span>Export Deal Sheet (.xlsx)</span>
            </button>

            <a
              href="/excel-viewer"
              onClick={(e) => { e.preventDefault(); navigateTo('/excel-viewer'); }}
              className="text-[11px] text-slate-400 hover:text-cyan-400 transition-colors flex items-center gap-1 sm:self-center"
            >
              <span>No Excel? In-Browser Viewer</span>
              <ArrowRight className="size-3" />
            </a>
          </div>
        </div>
      </div>

      {/* Balloon Maturity Risk Alert Banner */}
      {summary.hasBalloonPayment && (
        <div className={`p-6 rounded-2xl border mb-8 shadow-xl ${
          summary.refinanceRiskLevel === 'High'
            ? 'bg-amber-950/20 border-amber-500/40 shadow-amber-500/5'
            : 'bg-indigo-950/20 border-indigo-500/40'
        }`}>
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-6">
            <div className="space-y-2 max-w-3xl">
              <div className="flex items-center gap-2">
                <AlertTriangle className={`size-4 ${summary.refinanceRiskLevel === 'High' ? 'text-amber-400' : 'text-indigo-400'}`} />
                <span className={`text-xs font-bold uppercase tracking-wider ${summary.refinanceRiskLevel === 'High' ? 'text-amber-400' : 'text-indigo-400'}`}>
                  Year {summary.balloonTermYears} Balloon Due Notice ({summary.refinanceRiskLevel} Refinance Risk)
                </span>
              </div>
              <h2 className="text-xl sm:text-2xl font-bold text-slate-100">
                Lump Sum Balloon Due: ${summary.balloonDueAmount.toLocaleString()} ({summary.balloonDuePercentOfOriginal}% of original principal)
              </h2>
              <p className="text-sm text-slate-300 leading-relaxed">
                {summary.refinanceAnalysis}
              </p>
            </div>

            <div className="bg-slate-950/80 p-4 rounded-xl border border-slate-800 shrink-0 text-right min-w-[200px]">
              <span className="text-[11px] text-slate-400 block font-medium">Monthly Debt Service</span>
              <span className="text-2xl font-bold font-mono text-cyan-300">
                ${summary.regularMonthlyPayment.toLocaleString()}
              </span>
              <span className="text-[11px] text-slate-400 block mt-1">
                {inputs.amortizationYears}-Yr Amortization
              </span>
            </div>
          </div>
        </div>
      )}

      {/* Main Grid: Inputs vs Results */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 mb-12">
        {/* Left Inputs (7 cols) */}
        <div className="lg:col-span-7 p-6 rounded-2xl bg-slate-900/80 border border-slate-800 shadow-sm space-y-5">
          <div className="border-b border-slate-800 pb-3 flex items-center justify-between">
            <h3 className="text-base font-bold text-slate-100">Commercial Loan Parameters</h3>
            <span className="text-xs font-mono text-slate-400">Pure Local Processing</span>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className="block text-xs font-medium text-slate-300 mb-1.5">Property Purchase Price ($)</label>
              <CurrencyInput
                value={inputs.propertyPrice}
                onChange={(val) => setInputs({ ...inputs, propertyPrice: val })}
                className="focus:border-cyan-500"
              />
            </div>

            <div>
              <label className="block text-xs font-medium text-slate-300 mb-1.5">Down Payment (%)</label>
              <NumericInput
                value={inputs.downPaymentPercent}
                onChange={(val) => setInputs({ ...inputs, downPaymentPercent: val })}
                suffix="%"
                className="focus:border-cyan-500"
              />
              <span className="text-[11px] text-slate-400 mt-1 block">
                Cash Down: ${summary.downPaymentAmount.toLocaleString()} (Loan: ${summary.loanAmount.toLocaleString()})
              </span>
            </div>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            <div>
              <label className="block text-xs font-medium text-slate-300 mb-1.5">Interest Rate (APR %)</label>
              <NumericInput
                value={inputs.interestRate}
                onChange={(val) => setInputs({ ...inputs, interestRate: val })}
                suffix="%"
                className="focus:border-cyan-500"
              />
            </div>

            <div>
              <label className="block text-xs font-medium text-slate-300 mb-1.5">Amortization (Years)</label>
              <select
                value={inputs.amortizationYears}
                onChange={(e) => setInputs({ ...inputs, amortizationYears: Number(e.target.value) })}
                className="w-full px-3 py-2 bg-slate-950 border border-slate-800 rounded-xl text-sm font-semibold text-slate-100 focus:border-cyan-500 focus:outline-none"
              >
                <option value={15}>15 Years</option>
                <option value={20}>20 Years</option>
                <option value={25}>25 Years (Standard)</option>
                <option value={30}>30 Years</option>
              </select>
            </div>

            <div>
              <label className="block text-xs font-medium text-slate-300 mb-1.5">Balloon Term (Due In)</label>
              <select
                value={inputs.balloonTermYears}
                onChange={(e) => setInputs({ ...inputs, balloonTermYears: Number(e.target.value) })}
                className="w-full px-3 py-2 bg-slate-950 border border-slate-800 rounded-xl text-sm font-semibold text-slate-100 focus:border-cyan-500 focus:outline-none"
              >
                <option value={3}>3 Years</option>
                <option value={5}>5 Years (Typical CRE)</option>
                <option value={7}>7 Years</option>
                <option value={10}>10 Years</option>
                <option value={inputs.amortizationYears}>Fully Amortizing (No Balloon)</option>
              </select>
            </div>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 pt-2 border-t border-slate-800/80">
            <div>
              <label className="block text-xs font-medium text-slate-300 mb-1.5">Interest-Only Period</label>
              <select
                value={inputs.interestOnlyMonths}
                onChange={(e) => setInputs({ ...inputs, interestOnlyMonths: Number(e.target.value) })}
                className="w-full px-3 py-2 bg-slate-950 border border-slate-800 rounded-xl text-sm font-semibold text-slate-100 focus:border-cyan-500 focus:outline-none"
              >
                <option value={0}>0 Months (None)</option>
                <option value={12}>12 Months (1 Year)</option>
                <option value={24}>24 Months (2 Years)</option>
                <option value={36}>36 Months (3 Years)</option>
              </select>
            </div>

            <div>
              <label className="block text-xs font-medium text-slate-300 mb-1.5">Lender Points (%)</label>
              <NumericInput
                value={inputs.originationPoints ?? 0}
                onChange={(val) => setInputs({ ...inputs, originationPoints: val })}
                suffix="%"
                className="focus:border-cyan-500"
              />
            </div>

            <div>
              <label className="block text-xs font-medium text-slate-300 mb-1.5">Closing Fees ($)</label>
              <CurrencyInput
                value={inputs.closingFees ?? 0}
                onChange={(val) => setInputs({ ...inputs, closingFees: val })}
                className="focus:border-cyan-500"
              />
            </div>
          </div>
        </div>

        {/* Right Financial Metrics (5 cols) */}
        <div className="lg:col-span-5 p-6 rounded-2xl bg-slate-900/80 border border-slate-800 shadow-sm flex flex-col justify-between">
          <div>
            <h3 className="text-base font-bold text-slate-100 pb-3 mb-5 border-b border-slate-800">
              Debt Service & Equity Summary
            </h3>

            <div className="space-y-4">
              <div className="flex items-center justify-between pb-3 border-b border-slate-800/60">
                <span className="text-xs text-slate-400">Monthly P&I Debt Service</span>
                <span className="text-lg font-bold font-mono text-cyan-400">
                  ${summary.regularMonthlyPayment.toLocaleString()}/mo
                </span>
              </div>

              {Boolean(inputs.interestOnlyMonths) && (
                <div className="flex items-center justify-between pb-3 border-b border-slate-800/60">
                  <span className="text-xs text-slate-400">Initial IO Payment</span>
                  <span className="text-sm font-mono text-indigo-300">
                    ${summary.interestOnlyMonthlyPayment.toLocaleString()}/mo
                  </span>
                </div>
              )}

              <div className="flex items-center justify-between pb-3 border-b border-slate-800/60">
                <span className="text-xs text-slate-400">Upfront Points & Fees</span>
                <span className="text-sm font-mono text-slate-300">
                  ${summary.upfrontCosts.toLocaleString()}
                </span>
              </div>

              <div className="flex items-center justify-between pb-3 border-b border-slate-800/60">
                <span className="text-xs text-slate-400">Principal Paid by Balloon</span>
                <span className="text-sm font-mono text-emerald-400">
                  ${summary.totalPrincipalBeforeBalloon.toLocaleString()}
                </span>
              </div>

              <div className="flex items-center justify-between pb-3 border-b border-slate-800/60">
                <span className="text-xs text-slate-400">Interest Paid by Balloon</span>
                <span className="text-sm font-mono text-slate-300">
                  ${summary.totalInterestBeforeBalloon.toLocaleString()}
                </span>
              </div>

              <div className="flex items-center justify-between font-bold pt-1">
                <span className="text-xs text-slate-200">Balloon Maturity Lump Sum</span>
                <span className="text-base font-mono text-amber-400">
                  ${summary.balloonDueAmount.toLocaleString()}
                </span>
              </div>
            </div>
          </div>

          <div className="mt-8 p-4 rounded-xl bg-slate-950/80 border border-slate-800/80 text-xs text-slate-400 space-y-1">
            <div className="flex items-center gap-1.5 text-slate-200 font-medium mb-1">
              <ShieldCheck className="size-4 text-emerald-400" />
              <span>Institutional CRE Underwriting</span>
            </div>
            <p>Calculates standard US 30/360 commercial bank amortization with full transparency on balloon debt expiration.</p>
          </div>
        </div>
      </div>

      {/* Year-by-Year Amortization Schedule Table */}
      <div className="mb-14 rounded-2xl border border-slate-800 bg-slate-900/60 overflow-hidden shadow-lg">
        <div className="p-5 border-b border-slate-800 bg-slate-950/80 flex items-center justify-between">
          <h3 className="text-base font-bold text-slate-100">Annual Commercial Amortization Matrix</h3>
          <span className="text-xs text-slate-400 font-mono">Until Year {summary.balloonTermYears} Maturity</span>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left text-sm">
            <thead>
              <tr className="border-b border-slate-800 text-xs text-slate-400 bg-slate-950/40">
                <th className="p-4 font-semibold">Year</th>
                <th className="p-4 font-semibold">Annual Payments</th>
                <th className="p-4 font-semibold">Principal Paid</th>
                <th className="p-4 font-semibold">Interest Paid</th>
                <th className="p-4 font-semibold text-right">Remaining Loan Balance</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-800/60 text-xs">
              {summary.yearlySchedule.map((row) => (
                <tr key={row.year} className="hover:bg-slate-900/40">
                  <td className="p-4 font-mono font-medium text-slate-200">Year {row.year}</td>
                  <td className="p-4 font-mono text-slate-300">${row.paymentsTotal.toLocaleString()}</td>
                  <td className="p-4 font-mono text-emerald-400 font-medium">${row.principalTotal.toLocaleString()}</td>
                  <td className="p-4 font-mono text-slate-400">${row.interestTotal.toLocaleString()}</td>
                  <td className="p-4 font-mono text-right font-bold text-slate-100">
                    ${row.endingBalance.toLocaleString()}
                    {row.year === summary.balloonTermYears && summary.hasBalloonPayment && (
                      <span className="ml-2 text-[10px] px-1.5 py-0.5 rounded bg-amber-500/15 text-amber-400 border border-amber-500/30">
                        Balloon Due
                      </span>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* FAQs */}
      <div className="max-w-3xl mx-auto mb-12">
        <h2 className="text-xl sm:text-2xl font-bold text-slate-100 text-center mb-6">
          Commercial Loan & Balloon Payment FAQs
        </h2>
        <div className="space-y-3">
          {faqs.map((faq, index) => {
            const isOpen = openFaq === index;
            return (
              <div key={index} className="rounded-xl bg-slate-900/80 border border-slate-800 overflow-hidden">
                <button
                  onClick={() => setOpenFaq(isOpen ? null : index)}
                  className="w-full p-4 text-left flex items-center justify-between gap-4 cursor-pointer"
                >
                  <span className="text-sm font-semibold text-slate-200">{faq.q}</span>
                  <ChevronDown className={`size-4 text-slate-400 transition-transform ${isOpen ? 'rotate-180 text-cyan-400' : ''}`} />
                </button>
                {isOpen && (
                  <div className="px-4 pb-4 text-xs text-slate-400 leading-relaxed border-t border-slate-800/60 pt-3">
                    {faq.a}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>

      {/* Related Calculators Cross-Sell */}
      <div className="mb-12">
        <RelatedCalculators currentSlug="commercial-loan-calculator" category="real-estate" />
      </div>

      <MethodologyDisclosure type="commercial" />
      <AdSlot className="mt-8" />
    </div>
  );
};
